### ISSUE TITLE
The name `router` is ambiguous given its usage in other contexts

### ISSUE THREAD

**Issue by jtieri** [strangelove-ventures/packet-forward-middleware#10]
`router` is used in a few different contexts across modules/in the SDK so perhaps renaming to `ibcrouter` would be less confusing

**Comment by faddat** [comment]
yes, absolutely!

we could also call it pfm, that's what we usually call this software internally

**Comment by jtieri** [comment]
I think `pfm` or `forward` are valid choices! typically when I import the middleware into other repos I end up creating an alias called `forward` 

This codebase will soon be migrating to the new ibc-apps repo so maybe that becomes a good time to change the name away from `router`

**Comment by aljo242** [comment]
I think a lot of apps already rename the import to `packetforward` so this might be a good candidate as well.

**Comment by Reecepbcups** [comment]
Moved to upstream issue now in the maintained repo
