### ISSUE TITLE
v2.1.0 release module name

### ISSUE THREAD

**Issue by yaruwangway** [strangelove-ventures/packet-forward-middleware#15]
Hi @jtieri , i think go requires that module name in go.sum should be 

`module github.com/strangelove-ventures/packet-forward-middleware/v2` in order to import it by gaia or other app as tag v2.1.0?

https://github.com/strangelove-ventures/packet-forward-middleware/blob/2c91784afc35d770bcd76b0038ae4d14b84aa318/go.mod#L3

if this is true, all the self import should also add `v2`
like `"github.com/strangelove-ventures/packet-forward-middleware/v2/router/client/cli"`
https://github.com/strangelove-ventures/packet-forward-middleware/blob/2c91784afc35d770bcd76b0038ae4d14b84aa318/router/module.go#L25

sorry for this, i should have added in the pr. but please let me know if it is still possible that i can import v2.1.0 so that we do not need to make the change as above mentioned?

**Comment by jtieri** [comment]
Ahh you're right yaru. 

Upon bumping the major version number the module and import paths should have been changed to include `v2`

We can get that changed and re-tag appropriately/update the releases. I apologize for not paying closer attention!

**Comment by yaruwangway** [comment]
@jtieri actually ibc will do v3 release soon, in one hour, and there is some change make packet-forward module not compatible v2.1.0, how about packet forward module also bump to ibc-v3.0.0 with module name adding v2.
