### ISSUE TITLE
Add a simple binary for testing purposes

### ISSUE THREAD

**Issue by jtieri** [strangelove-ventures/packet-forward-middleware#27]
It would be convenient if we had a stripped down chain binary that includes the packet-forward-middleware so that we can use it for testing

**Comment by faddat** [comment]
True

**Comment by Reecepbcups** [comment]
This issue has now been moved to the upstream repo: https://github.com/cosmos/ibc-apps/issues/28. Will include PFM & ICQ for the CI there
