### ISSUE TITLE
Migrate PFM to `ibc-apps` repo

### ISSUE THREAD

**Issue by agouin** [strangelove-ventures/packet-forward-middleware#79]
Packet forward middleware should be added to [ibc-apps](https://github.com/cosmos/ibc-apps) with an accompanying sim app (to be created, can reference implementations such as [noble](https://github.com/strangelove-ventures/noble/pull/58), [juno](https://github.com/CosmosContracts/juno/pull/513), [osmosis](https://github.com/osmosis-labs/osmosis/pull/3911)) and [interchaintest case](https://github.com/strangelove-ventures/interchaintest/blob/main/examples/ibc/packet_forward_test.go)

**Comment by boojamya** [comment]
Waiting on backporting. Assigning: @boojamya

**Comment by boojamya** [comment]
Backporting done ✔️

**Comment by jtieri** [comment]
> Backporting done ✔️

Awesome! I should get PFM fully migrated next week as I will be OOO half of tomorrow and all of Friday.

**Comment by jtieri** [comment]
This has been completed ✅ 
- [v7](https://github.com/cosmos/ibc-apps/pull/30)
- [v6](https://github.com/cosmos/ibc-apps/pull/37)
- [v5](https://github.com/cosmos/ibc-apps/pull/38)
- [v4](https://github.com/cosmos/ibc-apps/pull/39)

At this point I think we should consider the v3 branch here unsupported given ibc-go/v3 has been EOL for awhile, so it doesn't make sense to move v3 to the ibc-apps repo as we don't even maintain a release/v3 branch there.

I have also opened up an issue [here](https://github.com/strangelove-ventures/packet-forward-middleware/issues/90) for archiving this repo/pointing users in the right direction for new issues and prs.
