### ISSUE TITLE
bump packet-forward-middleware to cosmos-sdk 0.45.1

### ISSUE THREAD

**Issue by yaruwangway** [strangelove-ventures/packet-forward-middleware#9]
For next [cosmoshub v07-Theta upgrade](https://github.com/cosmos/gaia/blob/main/docs/roadmap/cosmos-hub-roadmap-2.0.md#v7-theta-upgrade-expected-q1-2022):

we need `packet-forward-middleware` to bump to depend on [cosmos-sdk0.45.1](https://github.com/cosmos/cosmos-sdk/blob/v0.45.1/CHANGELOG.md#v0451---2022-02-03) or cosmos-sdk0.46 if cosmos-sdk 0.46 will be released much earlier before end of March.

Thank you!

**Comment by yaruwangway** [comment]
Hi @jackzampolin, we aim to cut a gaia release first week of March, if `packet-forward-middleware` bumping can meeting the time line ? presently, I used a fork of this repo. 😁

**Comment by jtieri** [comment]
Closed via #11
